const {test}=require('node:test'),assert=require('node:assert/strict');const {normalize,parseImage,generate}=require('../lib/ai.cjs');const {createHandler}=require('../api/generate.js');
const object={kind:'house',label:'집',color:'#aabbcc',x:1,y:0,z:1,rotation:0,scale:1};
test('AI output is normalized without extra code',()=>{const w=normalize({title:'마을',objects:[{...object,x:100,script:'bad'}]});assert.equal(w.objects[0].x,15);assert.equal(w.objects[0].script,undefined);assert.ok(w.objects[0].id);});
test('unsafe AI values are sanitized or dropped, never passed through',()=>{
 const w=normalize({title:'x',objects:[{...object,kind:'script'},{...object,color:'javascript:x'},{...object,color:'#abc'},{...object,x:NaN}]});
 assert.equal(w.objects.length,3);assert.equal(w.objects[0].kind,'box');assert.match(w.objects[1].color,/^#[0-9a-f]{6}$/);assert.equal(w.objects[2].color,'#aabbcc');
 assert.throws(()=>normalize({title:'x',objects:[{...object,x:NaN}]}));assert.throws(()=>normalize({title:'x',objects:'nope'}));});
test('new kinds are accepted; walk-through kinds are not solid; missing optional fields get defaults',()=>{
 const w=normalize({title:'x',inventory:['a'],objects:[{kind:'pond',color:'#3399ff',x:1,z:2},{kind:'mountain',label:'산',color:'#778899',x:0,z:-14,y:0,rotation:0,scale:9},{kind:'cloud',color:'#ffffff',x:3,z:3,y:8}]});
 assert.equal(w.objects[0].solid,false);assert.equal(w.objects[0].scale,1);assert.equal(w.objects[1].solid,true);assert.equal(w.objects[1].scale,2.5);assert.equal(w.objects[2].solid,false);assert.equal(w.inventory,undefined);});
test('non-images rejected',()=>assert.throws(()=>parseImage('data:image/png;base64,aGVsbG8=')));
function invoke(handler,body,authorization=''){return new Promise(resolve=>handler({method:'POST',headers:{'content-type':'application/json',authorization},body},{setHeader(){},end(body){resolve({code:this.statusCode,body:JSON.parse(body)});}}));}
test('disabled AI cannot call provider',async()=>{let calls=0;const r=await invoke(createHandler({env:{},generateImpl:()=>calls++}),{});assert.equal(r.code,403);assert.equal(calls,0);});
test('unauthorized or unapproved requests cannot call provider',async()=>{let calls=0;const secret='a'.repeat(32),env={AI_ENABLED:'true',APP_ACCESS_TOKEN:secret,GEMINI_API_KEY:'fake',GEMINI_MODEL:'gemini-test'};const h=createHandler({env,generateImpl:()=>calls++});assert.equal((await invoke(h,{})).code,401);assert.equal((await invoke(h,{},'Bearer '+secret)).code,403);assert.equal(calls,0);});
test('approved request uses injected provider once',async()=>{let calls=0;const secret='a'.repeat(32),env={AI_ENABLED:'true',APP_ACCESS_TOKEN:secret,GEMINI_API_KEY:'fake',GEMINI_MODEL:'gemini-test'};const h=createHandler({env,generateImpl:async()=>{calls++;return normalize({title:'test',objects:[object]});}});const image='data:image/png;base64,iVBORw0KGgo=';const r=await invoke(h,{approved:true,image},'Bearer '+secret);assert.equal(r.code,200);assert.equal(calls,1);});
test('provider 429 is not retried',async()=>{let calls=0;await assert.rejects(generate({key:'fake',model:'gemini-test',image:'data:image/png;base64,iVBORw0KGgo=',fetchImpl:async()=>{calls++;return {ok:false,status:429};}}));assert.equal(calls,1);});
test('request asks for JSON without a response schema (models reject it) and still validates output',async()=>{let body;const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';
 const out=await generate({key:'k',model:'gemini-test',image:png,fetchImpl:async(u,init)=>{body=JSON.parse(init.body);return {ok:true,status:200,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify({title:'t',objects:[{kind:'tree',label:'나무',color:'#aabbcc',x:1,y:0,z:2,rotation:0,scale:1}]})}]}}]})};}});
 assert.equal(body.generationConfig.responseMimeType,'application/json');assert.equal('responseJsonSchema' in body.generationConfig,false);assert.equal('responseSchema' in body.generationConfig,false);
 assert.match(body.systemInstruction.parts[0].text,/"kind":"house\|tree/);assert.equal(out.objects.length,1);});
